#spring:
#  datasource:
#    url: jdbc:h2:mem:olimpus
#    username: root
#    password: root1234
#  jpa:
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      ddl-auto: create # validade | update | create | create-drop
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olimpus_db
    username: postgres
    password: root1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect